# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a7314ae84139f89d0289de296fb9e19a"
extension_directories = [
  "../theme-extension",
  "../checkout-ui-extension",
  "../admin-block-extension"
]
name = "eu-blocks"
handle = "eu-blocks"
application_url = "https://supporters-man-proceeds-pichunter.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bennos-dev-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_locales,read_products,read_themes,write_files,write_products,write_themes"

[auth]
redirect_urls = [
  "https://supporters-man-proceeds-pichunter.trycloudflare.com/auth/callback",
  "https://supporters-man-proceeds-pichunter.trycloudflare.com/auth/shopify/callback",
  "https://supporters-man-proceeds-pichunter.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "unstable"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
