# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a7314ae84139f89d0289de296fb9e19a"
extension_directories = [ "../theme-extension" ]
name = "eu-blocks"
handle = "eu-blocks"
application_url = "https://liberal-rate-used-dates.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bennos-dev-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://liberal-rate-used-dates.trycloudflare.com/auth/callback",
  "https://liberal-rate-used-dates.trycloudflare.com/auth/shopify/callback",
  "https://liberal-rate-used-dates.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
