/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/shopify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/energy-label": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The current health status of the API:
         *     * `Up` - Fully operational
         *     * `Restricted` - Partially operational
         *     * `Down` - Not operational
         *
         * @enum {string}
         */
        HealthStatus: "Up" | "Restricted" | "Down";
        /** @example {
         *       "error_code": "#ERR_INVALID_INPUT",
         *       "error_description": "Invalid input",
         *       "error_uri": "https://api.builder.group/docs/errors#ERR_INVALID_INPUT",
         *       "additional_errors": []
         *     } */
        AppErrorDto: {
            /** @description Error code */
            error_code: string;
            /** @description Error description */
            error_description?: string;
            /** @description Error URI for more information */
            error_uri?: string | null;
            /** @description Additional error details */
            additional_errors?: Record<string, never>[];
        };
        /** @example {
         *       "status": "Up",
         *       "message": "API is functioning normally"
         *     } */
        HealthDto: {
            status: components["schemas"]["HealthStatus"];
            /** @description Additional health check information */
            message: string;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AppErrorDto"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AppErrorDto"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AppErrorDto"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AppErrorDto"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
