# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4fda1d00bc349ec079eecc278cb31fbb"
extension_directories = [ "../theme-extension", "../admin-block-extension" ]
name = "monorepo-test"
handle = "monorepo-test-1"
application_url = "https://residents-concepts-modify-expanding.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bennos-dev-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://residents-concepts-modify-expanding.trycloudflare.com/auth/callback",
  "https://residents-concepts-modify-expanding.trycloudflare.com/auth/shopify/callback",
  "https://residents-concepts-modify-expanding.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
